# Generated by Django 6.0.6 on 2026-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='type_lieu',
            field=models.CharField(choices=[('MARCHE', 'Marché'), ('HOPITAL', 'Hôpital'), ('ECOLE', 'École'), ('UNIVERSITE', 'Université'), ('ROUTE', 'Route principale'), ('GARE', 'Gare'), ('ARRET', 'Arrêt de bus'), ('ROND_POINT', 'Rond-point'), ('BATIMENT', 'Bâtiment public'), ('POUBELLE', 'Poubelle publique'), ('RECYCLAGE', 'Centre de recyclage'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
